name: Azure AI Service Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - ai/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai/requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd ai
          zip -r ../ai-deployment.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "${{ secrets.AZURE_AI_APP_NAME }}"
          publish-profile: ${{ secrets.AZURE_AI_WEBAPP_PUBLISH_PROFILE }}
          package: ./ai-deployment.zip
