name: Azure AI Service Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - ai/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai/requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd ai
          zip -r ../ai-deployment.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "cdc-team-ai"
          publish-profile: ${{ secrets.AZURE_AI_WEBAPP_PUBLISH_PROFILE }}
          package: ./ai-deployment.zip

      - name: Configure startup command
        uses: azure/appservice-settings@v1
        with:
          app-name: "cdc-team-ai"
          app-settings-json: |
            [
              {
                "name": "FLASK_APP",
                "value": "app.py"
              },
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "true"
              },
              {
                "name": "WEBSITE_RUN_FROM_PACKAGE",
                "value": "0"
              }
            ]
